### ISSUE TITLE
RSS feed 404

### ISSUE THREAD

**Issue by paulwakeford** [tedder/aws-release-notes-rss#1]
Hi Ted,

After several years of using this, the feed via tedder.me stopped working about 3 days ago.

See https://images.paulwakeford.info/ED4JULyxyh.png for the current results.

Will this be coming back or should I make other plans?

Thanks,

Paul

**Comment by tedder** [comment]
1. someone else actually uses this, cool.
2. I was cleaning up my S3 buckets. I obviously deleted the file, and the cron must not be running. I'll get this fixed in the next few hours.

**Comment by paulwakeford** [comment]
Great, thanks. The nature of RSS means there's not much interaction so I'll take this opportunity to say thanks very much for writing this code and hosting it for so long - I pipe it into a Flowdock channel to share with my colleagues and also am subscribed to it in Feedly. It's really useful.

**Comment by tedder** [comment]
hey Paul, I updated the code and deployed it, so things should be good now.

https://tedder.me/rss/aws-release-notes.xml

Glad to get feedback :) I could look at the s3 logs but I'm generally too lazy and distracted by other projects!

**Comment by paulwakeford** [comment]
Awesome, it's working again - thanks. A Cloudwatch alert for non-200 responses could work to save you log trawling.
